# Generated by Django 5.2.7 on 2025-10-13 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_activity_level_customer_age_customer_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='name',
            new_name='customer',
        ),
    ]
