# Generated by Django 5.2.7 on 2025-10-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customer_first_name_alter_customer_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='passwrod',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
