# Generated by Django 5.2.7 on 2025-10-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='daily_calories',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='goal',
            field=models.CharField(choices=[('lose', 'Lose Weight'), ('maintain', 'Maintain Weight'), ('gain', 'Gain Weight')], max_length=200, null=True),
        ),
    ]
