# Generated by Django 5.2.7 on 2025-11-05 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customer_daily_calories_alter_customer_goal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_goal', models.FloatField(null=True)),
                ('carb_ratio', models.FloatField(default=0.4)),
                ('protein_ratio', models.FloatField(default=0.3)),
                ('fat_ratio', models.FloatField(default=3.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutritional_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
