# Generated by Django 5.2.7 on 2025-12-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_meals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='date',
            field=models.DateField(),
        ),
    ]
